name: CI
on:
  push:
    branches:
      - main
env:
  PNPM_CACHE_FOLDER: .pnpm-store
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/cache@v2
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Use pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6
      - name: Setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER
      - name: Install dependencies
        run: pnpm install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Test
        run: pnpm run test
      - name: Build
        run: pnpm run build
      - name: Create release pull request or publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore: update versions"
          title: Update versions
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build changesets meta
        id: published
        uses: actions/github-script@v5
        env:
          PUBLISHED_PACKAGES: ${{ steps.changesets.outputs.publishedPackages }}
        with:
          script: |-
            const published = JSON.parse(process.env.PUBLISHED_PACKAGES);
            published.forEach(({ name }) => core.setOutput(name, 'true'));
      - name: Prepare gh-pages
        if: steps.published.outputs['@solsy/site'] == 'true'
        run: |-
          rm packages/site/dist/node_modules
          echo "/* /index.html 200" > packages/site/dist/_redirects
      - name: Deploy gh-pages
        if: steps.published.outputs['@solsy/site'] == 'true'
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: packages/site/dist
